services:
  db:
    image: postgres
    restart: always
    environment:
      # These variables should be defined in a .env file
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    profiles:
      - dev  # Adminer will only run in development
 
# Create a persistent volume to store db data even when the container is stopped or removed
volumes:
  pgdata: